workdir: "/data/share/htp/CZI_kidney/mouse_experiments/backgroundRNA/Snakemake"

# Input datasets
#dataset: ["rep1"]
dataset: ["rep1", "rep2", "rep3", "nuc2", "nuc3"]

# Parameter settings for different correction methods
cluster_res: [0.5,1,2]
#cluster_res: ["Default",0.5,1,2]

use_empty: [TRUE, FALSE]

set_cont: ["Auto",0.05,0.1,0.2]

total_droplets_included: [25000]

fpr: ["0.01", "0.1"]

# Evaluation
#method: ["DecontX", "SoupX"]
method: ["DecontX", "SoupX", "CellBender"]